import{S as i,i as c}from"./assets/vendor-46aac873.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const d=document.getElementById("search-form"),m=document.getElementById("gallery");var s=document.querySelector(".loader");s.style.display="none";d.addEventListener("submit",function(a){a.preventDefault(),s.style.display="block",setInterval(9e3);const r=document.getElementById("search-input").value;fetch(`https://pixabay.com/api/?key=41657052-3a9eaf34218752c6e4cd1bc6a&image_type=photo&per_page=90&q=${encodeURIComponent(r)}`).then(o=>o.json()).then(o=>{if(o.hits.length>0){const e=o.hits.map(t=>`<li class="gallery-item">
              <a class="gallery-link" href="${t.largeImageURL}">
            <img
              class="gallery-image"
              src="${t.webformatURL}"
              alt="${t.tags}"
            />
          </a>
        </li>`);m.innerHTML=e.join("");var n=new i(".gallery a",{captionsData:"alt",captionDelay:5e3,className:"modal-window-style"});n.on("show.simplelightbox",function(t){}),s.style.display="none"}else c.info({transitionIn:"fadeInLeft",theme:"dark",messageColor:"#FAFAFB",backgroundColor:"#B51B1B",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),s.style.display="none"}).catch(o=>console.error(o)),lightbox.refresh()});
//# sourceMappingURL=commonHelpers.js.map
